name: Android CI

on: [ label, release, push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./build.sh ${{secrets. CODACY_TOKEN}}

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Releases"
          path: "./build/publications"
 
