@startuml

(*) -D-> "//on//" as On

On -D-> "//event//" as onEvent
On -D-> "//stateEnter//" as onStateEnter
On -D-> "//stateExit//" as onStateExit

onEvent -D-> "**__EVENT__**" as  EVENT1
EVENT1 -D-> "//withState//" as withState
withState -D-> "**__STATE__**" as STATE1

EVENT1 -D-> "//execute//" as Execute 
STATE1-D-> "//execute//" as Execute 
EVENT1 -D-> "//set//" as Set1
STATE1-D-> "//set//" as Set1 
STATE1-D-> "//executeAndSet//" as ExecuteAndSet 
EVENT1 -D-> "//executeAndSet//" as ExecuteAndSet

onStateEnter -D-> "**__STATE__**" as STATE2
onStateExit -D-> "**__STATE__**" as STATE2

Execute -D-> (*)
Set1 -D-> "**__STATE__**" as STATE2
ExecuteAndSet -D-> "**__STATE__**" as STATE2
STATE2 -D-> (*)


(*) -D-> "//set//" as Set2

Set2 -D-> "**__EVENT__**" as EVENT2
EVENT2 -D-> "//withData//" as WithData
WithData -D-> "**__DATA__**" as Data

EVENT2 -D-> (*)
Data -D-> (*)

@enduml