@startuml

(*) -D-> "**+**" as Enter

"**+**" as Enter -D-> "Event" as Event0
"**+**" as Enter -D-> "State" as State0
"**+**" as Enter -D-> "EventGroup" as EventGroup0
"**+**" as Enter -D-> "StateGroup" as StateGroup0

Event0 -D-> "*****" as TIMES0
EventGroup0 -D-> "*****" as TIMES0
State0 -D-> "*****" as TIMES0
StateGroup0 -D-> "*****" as TIMES0

TIMES0 -D-> "Data" as Data0

Data0 -D-> "**+**" as PLUS0
"**+**" as PLUS0 -D-> "Event" as Event1
"**+**" as PLUS0 -D-> "State" as State1
"**+**" as PLUS0 -D-> "EventGroup" as EventGroup1
"**+**" as PLUS0 -D-> "StateGroup" as StateGroup1
@enduml