name: Android CI

on: [push]

jobs:
  build:

    runs-on: [self-hosted]
    
    steps:
    - uses: actions/checkout@v2
    - name: setup-android
      uses: msfjarvis/setup-android@0.2
    - name: Build with Gradle
      run: ./gradlew clean assemble
