name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew test publishToMavenLocal
#    - name: FTP-Deploy-Action
#      uses: SamKirkland/FTP-Deploy-Action@3.0.0
#      with:
#        ftp-server: ftp://zieger.dev/
#        ftp-username: user
#        ftp-password: ${{ secrets.FTP_PASSWORD }}
#        local-dir: build
#        git-ftp-args: --insecure
        
