name: Android CI

on: [label, release, push, pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Build with Gradle
      run: ./gradlew build jacocoTestReport publishToMavenLocal
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
         name:  "Releases"
         path:  "./build/publications"  
 
    - name: Codeclimate
      uses: paambaati/codeclimate-action@v2.6.0
      env:
         CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_TOKEN}}
         JACOCO_SOURCE_PATH: "${{github.workspace}}/core/src/main/kotlin"
      with:
        coverageCommand: ./gradlew test jacocoTestReport
        coverageLocations:  ./core/build/jacoco/test/jacocoTestReport.xml:jacoco
  
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        name: "Utils coverage"
        file: "${{github.workspace}}/core/build/jacoco/test/jacocoTestReport.xml"
        token:  ${{ secrets.CODECOV_TOKEN }}
    
    - name: Codacy
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{secrets.CODACY_TOKEN}}
        coverage-reports: ./core/build/jacoco/test/jacocoTestReport.xml

#    - name: FTP-Deploy-Action
#      uses: SamKirkland/FTP-Deploy-Action@3.0.0
#      with:
#        ftp-server: ftp://zieger.dev/
#        ftp-username: user
#        ftp-password: ${{ secrets.FTP_PASSWORD }}
#        local-dir: build
#        git-ftp-args: --insecure
        
