name: Android CI

on: [label, release, push, pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build jacocoTestReport publishToMavenLocal
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        name: "Utils coverage"
        file: "./core/build/jacoco/test/jacocoTestReport.xml"
        token:  ${{ secrets.CODECOV_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
         name:  "Releases"
         path:  "./build/publications"
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
         # Set CC_TEST_REPORTER_ID as secret of your repo
         CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
         JACOCO_SOURCE_PATH: "./core/src/main/kotlin"
      with:
        # The report file must be there, otherwise Code Climate won't find it
        coverageCommand: ./gradlew test jacocoTestReport
        coverageLocations: ./core/build/jacoco/test/jacocoTestReport.xml:jacoco
#    - name: FTP-Deploy-Action
#      uses: SamKirkland/FTP-Deploy-Action@3.0.0
#      with:
#        ftp-server: ftp://zieger.dev/
#        ftp-username: user
#        ftp-password: ${{ secrets.FTP_PASSWORD }}
#        local-dir: build
#        git-ftp-args: --insecure
        
