name: CI

on: [push]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: ./gradlew clean publishToMavenLocal
